package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
	"time"
)

// ─── The differential that makes the storage change trustworthy ───────────────
//
// The band-key storage model was proven in a spike by comparing its output
// CELL FOR CELL against the row-keyed implementation running on a byte-identical
// copy of the same sheet. Once the spike BECOMES the implementation that
// comparison has nothing to run against — so the expected answers were pinned
// here as fixtures FIRST, computed by the old row-keyed code, and are asserted
// against afterwards. The hashes below are therefore a record of what
// `PRIMARY KEY ("row", col)` produced, checked against what
// `PRIMARY KEY (k, col)` produces.
//
// What is hashed is deliberately the PUBLIC, DISPLAY-SPACE surface — Window,
// GetCell, DependentsOf, PrecedentsOf, Events, ColWidths — and nothing about
// storage. A fixture that hashed keys would have had to be regenerated by the
// change it exists to police.
//
// THE SAME SEVEN HASHES HAVE NOW MOVED TWICE, IN OPPOSITE DIRECTIONS, and every
// one of them is a DELETE. The reason is one number and it is not about cells: a
// row delete gives its rows back only down to a DefaultRows floor.
//
//	10,000 -> 1,000   the floor dropped far below the fixture's extent, so a
//	                  delete now shrank the grid (delete one row, extent 9,999)
//	1,000 -> 10,000   the floor is the fixture's extent again, so a delete gives
//	                  the row straight back and the extent does not move
//
// The last golden window reaches past the bottom of the sheet ON PURPOSE, which
// is why a grid that is n rows shorter shows up at all: its cell count is the
// rows that exist inside the window, so it falls and rises by 26 per row.
//
// CHECKED, NOT ASSUMED, both times, by the same method. Taking each new dump and
// patching ONLY the last window's cell count back to its previous value
// reproduces the OLD hash byte for byte, and EXACTLY ONE LINE differs in each of
// the seven. Measured on the way back up:
//
//	DeleteRows(0,1)                   2574 -> 2600 cells   (1 row x 26)
//	DeleteRows(48,4) band edge        2496 -> 2600         (4 rows)
//	DeleteRows(60,120) whole bands       0 -> 2600         (the window was past the end)
//	insert then delete the same row   2574 -> 2600         (net one row)
//	interleaved edits and structure   2548 -> 2600         (net two rows)
//	rows then cols                    2574 -> 2600         (net one row)
//	FullSheet DeleteRows(0,1)         7774 -> 7800         (window 9700..9999)
//
// No cell moved, no value changed, no event changed, no width changed and no
// dependency edge changed — the sheets are identical and only the grid they sit
// in is a different height. The other NINE hashes did not move in either
// direction, which is goldenExtent doing its job.
//
// Regenerate (only ever against a version you have separately established to be
// correct) with:
//
//	SSGOLDEN=1 go test -run 'TestStructuralGolden' -v
//
// THREE HASHES WERE REGENERATED WHEN THE STORAGE MODEL CHANGED, and since the
// point of a fixture is that it does not move, here is exactly what moved and
// how it was checked. In `InsertRows(1,3)`, `InsertRows(75,2)` and the
// 60-inserts case — the three where a stored RANGE straddles the insertion
// point — the two implementations disagree about two cells and only two cells:
// Y151 and the Y201 that reads it.
//
// The row-keyed implementation had to rewrite a straddling range's endpoints,
// so it recomputed the formula as a side effect. The band-key implementation
// does not touch it: the range expands over rows that are BLANK BY
// CONSTRUCTION, so a SUM over it cannot change value, and not writing is the
// entire point. The reason the two answers differ anyway is that the seeded
// fixture stores a WRONG value for Y151 (see seedColY in store.go: the layout
// comment claims only Y1 and Y51 fall inside SUM(Y1:Y101), but Y101 is the last
// row of that span and holds 2,790). So the old code was accidentally REPAIRING
// a stale fixture value, and the new code leaves it exactly as stale as it
// found it.
//
// Checked rather than argued: taking the new dump for each of the three cases
// and patching those two cells to the values the old code produced reproduces
// the OLD hash byte for byte. TestExpandedRangeKeepsItsValue pins the behaviour
// on a sheet whose values are consistent to begin with, and
// TestMutationAddsNoStaleValues pins that no mutation ever leaves MORE stale
// values behind than it found.

// goldenDump renders every user-visible fact about a sheet as one canonical
// string: the cells of the windows given, the whole event log (minus its
// timestamps, which are not reproducible), the column widths, and both
// dependency directions for a set of probe cells.
func goldenDump(t *testing.T, sh *Sheet, windows [][2]int, probes []string) string {
	t.Helper()
	var sb strings.Builder
	for _, w := range windows {
		cells, err := sh.Window(w[0], w[1])
		if err != nil {
			t.Fatalf("golden window %v: %v", w, err)
		}
		fmt.Fprintf(&sb, "# window %d..%d (%d cells)\n", w[0], w[1], len(cells))
		for _, c := range cells {
			if c.Kind == KindEmpty && c.Raw == "" && c.Computed == "" {
				continue
			}
			fmt.Fprintf(&sb, "%s|%s|%s|%d\n", c.Ref, c.Raw, c.Computed, int(c.Kind))
		}
	}

	// probes == nil means "cells only": used to compare two sheets that reached
	// the same state by different routes and therefore have different logs.
	if probes == nil {
		return sb.String()
	}

	sb.WriteString("# events\n")
	evs, err := sh.Events(0, 100000)
	if err != nil {
		t.Fatalf("golden events: %v", err)
	}
	for _, e := range evs {
		fmt.Fprintf(&sb, "%d|%s|%s|%s\n", e.Seq, e.Ref, e.Raw, e.Prev)
	}

	sb.WriteString("# widths\n")
	w, err := sh.ColWidths()
	if err != nil {
		t.Fatalf("golden widths: %v", err)
	}
	cols := make([]int, 0, len(w))
	for c := range w {
		cols = append(cols, c)
	}
	sort.Ints(cols)
	for _, c := range cols {
		fmt.Fprintf(&sb, "%d=%d\n", c, w[c])
	}

	sb.WriteString("# graph\n")
	for _, a1 := range probes {
		ref := mustRef(t, a1)
		dep, err := sh.DependentsOf(ref)
		if err != nil {
			t.Fatalf("golden dependents %s: %v", a1, err)
		}
		prec, err := sh.PrecedentsOf(ref)
		if err != nil {
			t.Fatalf("golden precedents %s: %v", a1, err)
		}
		fmt.Fprintf(&sb, "%s dep=[%s] prec=[%s]\n", a1,
			strings.Join(refStrings(dep), " "), strings.Join(refStrings(prec), " "))
	}
	return sb.String()
}

// goldenCheck hashes a dump and compares it with the pinned value. On a
// mismatch the whole dump is written next to the test binary so the difference
// can be found by diffing two runs rather than by reading a hash.
func goldenCheck(t *testing.T, name, want, dump string) {
	t.Helper()
	sum := sha256.Sum256([]byte(dump))
	got := hex.EncodeToString(sum[:])
	if os.Getenv("SSGOLDEN") != "" {
		t.Logf("GOLDEN %-28s %s (%d bytes)", name, got, len(dump))
		return
	}
	if got != want {
		path := filepath.Join(os.TempDir(), "golden-"+strings.NewReplacer("/", "_", " ", "_").Replace(name)+".txt")
		if err := os.WriteFile(path, []byte(dump), 0o644); err == nil {
			t.Errorf("%s: dump hash %s, want %s (dump written to %s)", name, got, want, path)
		} else {
			t.Errorf("%s: dump hash %s, want %s", name, got, want)
		}
	}
}

// goldenExtent is the ALLOCATED ROW HEIGHT every fixture in this file is
// pinned against, stated explicitly instead of inherited from DefaultRows.
//
// It used to be inherited, and that was a latent bug in the fixtures rather
// than a convenience: Cache.Seed sizes a sheet to max(seededRows, DefaultRows),
// so a 300-row fixture silently became however tall the default happened to be,
// and goldenWindows probes rows 9900..9999 — which exist only because the
// default was 10,000. Lowering DefaultRows to a blank Google Sheet's 1,000
// would therefore have moved all sixteen hashes for a reason that has nothing
// to do with storage, and regenerating them would have thrown away the one
// piece of evidence that the band-key model is cell-for-cell faithful to the
// row-keyed model it replaced.
//
// Stated here, the fixtures pin the grid they always meant, the hashes do not
// move when the default does, and the constant is free to be what a new sheet
// should start at. THE HASHES BELOW ARE UNCHANGED FROM THE ROW-KEYED
// IMPLEMENTATION; nothing in this file was regenerated for it.
//
// ensureRows reproduces the old shape exactly rather than approximately: growTo
// lays out CANONICAL bands, and growing a 1,000-row canonical layout to 10,000
// appends bands at exactly the bases layoutFor(10000) would have given them, so
// every key in the fixture is the key it was.
const goldenExtent = 10000

// goldenWindows are the display rows the fixtures cover: the top of the sheet
// (where content moves), a band boundary in the middle, and the LAST rows of
// the grid — which is where an insert pushes content off the end and a delete
// opens blank rows up, the two places a storage change is most likely to be
// quietly wrong.
var goldenWindows = [][2]int{{0, 399}, {4900, 5000}, {9900, 9999}}

var goldenProbes = []string{"A1", "A2", "A51", "A52", "U1", "V1", "W1", "W51",
	"X51", "Y1", "Y51", "Y101", "Y151", "Y201", "A200", "A9999"}

// goldenCase is one mutation sequence with the hash of the sheet it leaves
// behind.
type goldenCase struct {
	name string
	rows int
	// hash of goldenDump after apply.
	hash  string
	apply func(t *testing.T, sh *Sheet)
}

// mustExtent grows a freshly seeded fixture to the height its hash was taken
// at. It is a no-op when the seed was already that tall or taller.
func mustExtent(t *testing.T, sh *Sheet, rows int) {
	t.Helper()
	if err := sh.ensureRows(rows); err != nil {
		t.Fatalf("grow fixture to %d rows: %v", rows, err)
	}
	if got := sh.Rows(); got != rows {
		t.Fatalf("fixture is %d rows tall, want %d", got, rows)
	}
}

func mut(t *testing.T, name string, d Dirty, err error) {
	t.Helper()
	if err != nil {
		t.Fatalf("%s: %v", name, err)
	}
	_ = d
}

var structuralGoldenCases = []goldenCase{
	{
		name: "untouched seed", rows: 300,
		hash:  "528794ed0342b72bbcb1a59d49e0fe71c4ce7c32e4bf9acc376f6d9c20a393da",
		apply: func(t *testing.T, sh *Sheet) {},
	},
	{
		name: "InsertRows(0,1)", rows: 300,
		hash: "b831999f277b5feeb72824e3737d42a35ac2bd5dac240eb504645ffdb409e766",
		apply: func(t *testing.T, sh *Sheet) {
			d, err := sh.InsertRows(0, 1)
			mut(t, "InsertRows(0,1)", d, err)
		},
	},
	{
		name: "InsertRows(1,3)", rows: 300,
		hash: "6e4b8a39d28162ba578bc203dc326e87695ad00f4635dc2e892f6a25c286cb9d",
		apply: func(t *testing.T, sh *Sheet) {
			d, err := sh.InsertRows(1, 3)
			mut(t, "InsertRows(1,3)", d, err)
		},
	},
	{
		name: "InsertRows(mid band)", rows: 300,
		hash: "9a929136e97debfaf7552d686ed832514a60a1e68e094e0e549c7b422d95edc1",
		apply: func(t *testing.T, sh *Sheet) {
			d, err := sh.InsertRows(75, 2)
			mut(t, "InsertRows(75,2)", d, err)
		},
	},
	{
		name: "DeleteRows(0,1)", rows: 300,
		hash: "b9f47d822f530a62f828e0905e57efd69ea9b116987ce3666be5fb0efc1d617e",
		apply: func(t *testing.T, sh *Sheet) {
			d, err := sh.DeleteRows(0, 1)
			mut(t, "DeleteRows(0,1)", d, err)
		},
	},
	{
		name: "DeleteRows(48,4) across a band edge", rows: 300,
		hash: "8a1697f315f128b8d647bd6887cdda7b49d5f4b5f5550708303c8fd5eec6aeb5",
		apply: func(t *testing.T, sh *Sheet) {
			d, err := sh.DeleteRows(48, 4)
			mut(t, "DeleteRows(48,4)", d, err)
		},
	},
	{
		name: "DeleteRows(60,120) across whole bands", rows: 300,
		hash: "b7ca1f8f5921ee7c5d759549902a1737fc893370834a10e612a94e5123765bda",
		apply: func(t *testing.T, sh *Sheet) {
			d, err := sh.DeleteRows(60, 120)
			mut(t, "DeleteRows(60,120)", d, err)
		},
	},
	{
		name: "insert then delete the same row", rows: 300,
		hash: "18670a6bc9581e7eda734df4b1dadc88fc3552165cd8b6429c5f5434ed856398",
		apply: func(t *testing.T, sh *Sheet) {
			d, err := sh.InsertRows(10, 1)
			mut(t, "InsertRows(10,1)", d, err)
			d, err = sh.DeleteRows(10, 1)
			mut(t, "DeleteRows(10,1)", d, err)
		},
	},
	{
		name: "many inserts at one position", rows: 300,
		hash: "dcc514013a9a4aa21aae4a62d1ead4b7cff3f4733151fff321eada5e84ca802b",
		apply: func(t *testing.T, sh *Sheet) {
			for i := 0; i < 60; i++ {
				d, err := sh.InsertRows(25, 1)
				mut(t, "InsertRows(25,1)", d, err)
			}
		},
	},
	{
		name: "interleaved edits and structure", rows: 300,
		hash: "55ec62de842a1e8ad313f23d7eb68fdcc74eade52ac0e5bf98a6b3b2e24bff57",
		apply: func(t *testing.T, sh *Sheet) {
			mustSet(t, sh, "Z1", "=SUM(A1:A10)")
			d, err := sh.InsertRows(5, 1)
			mut(t, "InsertRows(5,1)", d, err)
			mustSet(t, sh, "Z2", "=Z1*2")
			d, err = sh.DeleteRows(3, 2)
			mut(t, "DeleteRows(3,2)", d, err)
			mustSet(t, sh, "A1", "1234")
		},
	},
	{
		name: "InsertCols(1,1)", rows: 300,
		hash: "aa5b56761cf3bad2e4c441c04d7ee18543fbe185269f83aa1d535046cf763ec9",
		apply: func(t *testing.T, sh *Sheet) {
			if err := sh.SetColWidth(2, 200); err != nil {
				t.Fatalf("SetColWidth: %v", err)
			}
			d, err := sh.InsertCols(1, 1)
			mut(t, "InsertCols(1,1)", d, err)
		},
	},
	{
		name: "DeleteCols(0,2)", rows: 300,
		hash: "65029e93e7d0bf050c12d3e18b41ba40c78ca937c03db5c91d4f482f2858cf31",
		apply: func(t *testing.T, sh *Sheet) {
			if err := sh.SetColWidth(2, 200); err != nil {
				t.Fatalf("SetColWidth: %v", err)
			}
			d, err := sh.DeleteCols(0, 2)
			mut(t, "DeleteCols(0,2)", d, err)
		},
	},
	{
		name: "rows then cols", rows: 300,
		hash: "75424564d922f5a5d5ec11c69f85456e246f212505c1a4d1265742e6b805e7f1",
		apply: func(t *testing.T, sh *Sheet) {
			d, err := sh.InsertRows(0, 2)
			mut(t, "InsertRows(0,2)", d, err)
			d, err = sh.DeleteCols(20, 1)
			mut(t, "DeleteCols(20,1)", d, err)
			d, err = sh.DeleteRows(1, 1)
			mut(t, "DeleteRows(1,1)", d, err)
		},
	},
}

// TestStructuralGolden runs every mutation shape against a seeded sheet and
// checks the resulting sheet against a hash taken from the previous storage
// model. It is the regression net under the whole band-key promotion.
func TestStructuralGolden(t *testing.T) {
	for _, tc := range structuralGoldenCases {
		t.Run(tc.name, func(t *testing.T) {
			c := newTestCache(t, 4, time.Minute)
			sh := mustSeed(t, c, "golden", tc.rows, MaxCols)
			mustExtent(t, sh, goldenExtent)
			tc.apply(t, sh)
			goldenCheck(t, tc.name, tc.hash, goldenDump(t, sh, goldenWindows, goldenProbes))
		})
	}
}

// fullSheetGoldenCases are the three headline operations from the cost work, on
// the full 9,999-row fixture the measurements use, over the windows the spike
// verified cell for cell.
var fullSheetGoldenCases = []struct {
	name string
	hash string
	del  bool
	at   int
}{
	{name: "InsertRows(0,1)", at: 0, hash: "4b39f37c579b0ba37ee0272413f85f35bb09b0702c58083aa764d5e3213784a6"},
	{name: "InsertRows(9500,1)", at: 9500, hash: "50b2945601bd07025604fb334d094529777f457eabbd9e932917c7721c2b7f61"},
	{name: "DeleteRows(0,1)", at: 0, del: true, hash: "910bf7c6f01a2b85efa32aa64037b84e83129f5af048972b21aeebf32dba0c51"},
}

var fullGoldenWindows = [][2]int{{0, 299}, {4900, 5200}, {9700, 9999}}

// TestStructuralGoldenFullSheet is the same differential on the real fixture:
// 9,999 x 26, 220,382 cells, the sheet every number in DATA-MODEL.md was taken
// on. Skipped under -short because it seeds four full sheets.
func TestStructuralGoldenFullSheet(t *testing.T) {
	if testing.Short() {
		t.Skip("seeds a full sheet; skipped under -short")
	}
	for _, tc := range fullSheetGoldenCases {
		t.Run(tc.name, func(t *testing.T) {
			c := newTestCache(t, 4, time.Minute)
			sh := mustSeed(t, c, "goldenfull", goldenExtent-1, MaxCols)
			mustExtent(t, sh, goldenExtent)
			var err error
			if tc.del {
				_, err = sh.DeleteRows(tc.at, 1)
			} else {
				_, err = sh.InsertRows(tc.at, 1)
			}
			if err != nil {
				t.Fatalf("%s: %v", tc.name, err)
			}
			goldenCheck(t, tc.name, tc.hash, goldenDump(t, sh, fullGoldenWindows, goldenProbes))
		})
	}
}
